-- MySQL Script generated by MySQL Workbench
-- Tue Oct 11 21:58:49 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`agencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`agencia` (
  `nome_agencia` VARCHAR(100) NOT NULL,
  `cidade_agencia` VARCHAR(45) NOT NULL,
  `ativo` INT NOT NULL,
  PRIMARY KEY (`nome_agencia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`funcionario` (
  `id_funcionario` INT NOT NULL,
  `nome_funcionario` VARCHAR(100) NOT NULL,
  `numero_telefone` INT NULL,
  `data_admissao` DATE NOT NULL,
  `tempo_servico` INT NULL,
  `funcionario_id_funcionario` INT NOT NULL,
  PRIMARY KEY (`id_funcionario`),
  INDEX `fk_funcionario_funcionario1_idx` (`funcionario_id_funcionario` ASC) VISIBLE,
  CONSTRAINT `fk_funcionario_funcionario1`
    FOREIGN KEY (`funcionario_id_funcionario`)
    REFERENCES `mydb`.`funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `id_cliente` INT NOT NULL,
  `nome_cliente` VARCHAR(100) NOT NULL,
  `rua_cliente` VARCHAR(45) NULL,
  `cidade_cliente` VARCHAR(45) NULL,
  `funcionario_id_funcionario` INT NOT NULL,
  PRIMARY KEY (`id_cliente`),
  INDEX `fk_cliente_funcionario1_idx` (`funcionario_id_funcionario` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_funcionario1`
    FOREIGN KEY (`funcionario_id_funcionario`)
    REFERENCES `mydb`.`funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`emprestimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`emprestimo` (
  `numero_emprestimo` INT NOT NULL,
  `quantia` DOUBLE NOT NULL,
  `emprestimocol` VARCHAR(45) NOT NULL,
  `agencia_nome_agencia` VARCHAR(100) NOT NULL,
  `cliente_id_cliente` INT NOT NULL,
  PRIMARY KEY (`numero_emprestimo`),
  INDEX `fk_emprestimo_agencia_idx` (`agencia_nome_agencia` ASC) VISIBLE,
  INDEX `fk_emprestimo_cliente1_idx` (`cliente_id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_emprestimo_agencia`
    FOREIGN KEY (`agencia_nome_agencia`)
    REFERENCES `mydb`.`agencia` (`nome_agencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emprestimo_cliente1`
    FOREIGN KEY (`cliente_id_cliente`)
    REFERENCES `mydb`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pagamento` (
  `numero_pagamento` INT NOT NULL,
  `data_pagamento` DATE NOT NULL,
  `quantia_pagamento` DOUBLE NOT NULL,
  `emprestimo_numero_emprestimo` INT NOT NULL,
  PRIMARY KEY (`numero_pagamento`, `emprestimo_numero_emprestimo`),
  INDEX `fk_pagamento_emprestimo1_idx` (`emprestimo_numero_emprestimo` ASC) VISIBLE,
  CONSTRAINT `fk_pagamento_emprestimo1`
    FOREIGN KEY (`emprestimo_numero_emprestimo`)
    REFERENCES `mydb`.`emprestimo` (`numero_emprestimo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dependente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dependente` (
  `nome_dependente` VARCHAR(100) NOT NULL,
  `funcionario_id_funcionario` INT NOT NULL,
  PRIMARY KEY (`nome_dependente`, `funcionario_id_funcionario`),
  INDEX `fk_dependente_funcionario1_idx` (`funcionario_id_funcionario` ASC) VISIBLE,
  CONSTRAINT `fk_dependente_funcionario1`
    FOREIGN KEY (`funcionario_id_funcionario`)
    REFERENCES `mydb`.`funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`conta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`conta` (
  `numero_conta` INT NOT NULL,
  `saldo` DOUBLE NOT NULL,
  `tipo_conta` VARCHAR(45) NOT NULL,
  `agencia_nome_agencia` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`numero_conta`),
  INDEX `fk_conta_agencia1_idx` (`agencia_nome_agencia` ASC) VISIBLE,
  CONSTRAINT `fk_conta_agencia1`
    FOREIGN KEY (`agencia_nome_agencia`)
    REFERENCES `mydb`.`agencia` (`nome_agencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`depositante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`depositante` (
  `cliente_id_cliente` INT NOT NULL,
  `conta_numero_conta` INT NOT NULL,
  `data_acesso` DATE NOT NULL,
  PRIMARY KEY (`cliente_id_cliente`, `conta_numero_conta`),
  INDEX `fk_cliente_has_conta_conta1_idx` (`conta_numero_conta` ASC) VISIBLE,
  INDEX `fk_cliente_has_conta_cliente1_idx` (`cliente_id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_has_conta_cliente1`
    FOREIGN KEY (`cliente_id_cliente`)
    REFERENCES `mydb`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_has_conta_conta1`
    FOREIGN KEY (`conta_numero_conta`)
    REFERENCES `mydb`.`conta` (`numero_conta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`conta_poupanca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`conta_poupanca` (
  `taxa_juros` DOUBLE NOT NULL,
  `conta_numero_conta` INT NOT NULL,
  PRIMARY KEY (`conta_numero_conta`),
  CONSTRAINT `fk_conta_poupanca_conta1`
    FOREIGN KEY (`conta_numero_conta`)
    REFERENCES `mydb`.`conta` (`numero_conta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`conta_corrente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`conta_corrente` (
  `quantia_saque_descoberto` DOUBLE NOT NULL,
  `conta_numero_conta` INT NOT NULL,
  PRIMARY KEY (`conta_numero_conta`),
  CONSTRAINT `fk_conta_corrente_conta1`
    FOREIGN KEY (`conta_numero_conta`)
    REFERENCES `mydb`.`conta` (`numero_conta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
